generalidad deseable: distancia temporal y espacial de eventos para que haya transmision. Funcion que diga como cambia la prob de transmision en function del tiempo y distancia entre agentes. 

Potencialmente contemplar anisotropía del espacio


dado que estoy en un tipo de comportamiento


de una distribucion dice cuanto tiempo me muevo en una direccion # Ponerle un counter al agente?

de otra distribucion dice en que velocidad me muevo. 


mas simple: vel constante pero varia entre comportamientos. Distribucion de waiting times tambien cambia por comportamiento. 



Waiting times es la cant de dts que pasas en un angulo en particular.




Markers: 
size of the markers could be internal state. #  as(a) = 0.5*a.internal_state
shape of the markers could be behaviour # am(a) = a.status == :S ? :circle : a.status == :I ? :diamond : :rect
color of the markers could be infectious state. # ac(a) = a.status == :S ? "#2b2b33" : a.status == :I ? "#bf2642" : "#338c54"




Parameters to optimize with blackbox optim? 
- Time when to vaccinate? # do vaccines have a cost?
- Fitness
- Money for farmers?





What happens if we deny the access to a spot with fasciola?



Dist de cambio de comportamiento?














Notes from Hooten et al 2010. 

More recently, Tracey, Zhu, and Crooks (2005) presented a model-based egocentric approach that links turn angles and move distances to known landscape features, and they are in the process of generalizing these methods to accommodate covariates and multi-animal inference using artificial neural networks (Tracey, Zhu, and Crooks 2010).






Similar a gillespie -> discrete event simulation



ver DiscreteEvents.jl, hablarlo con George. 


Olvidarnos del dt de Agents, nos permitiria 



Cuestiones dt: 
- Gracia de 




La idea es que vaya hacer ceirta activdad por 


ornstein ullenbeck es un proceso estocastico en tiempo continuo que basicamente te da una distr normal bivariada si fuese en un esppacio. 

Si usas ornstein ullenbeck para modelar la velocidad. 



La parte mas importante de movimiento colectivo es que no se dispersen los bichos. 







Decisiones de codigo/modelo: cuestiones de habitat selection (ver paper en el que esta john fiber y abgar (no son primeros autores) sobre habitat selection. El paper es una especie de How-To, tiene buena interpretacion y fundamentos. ver este paper https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13441) y de collective movement (que modelo se va a implementar de esto se va a charlar con Fernando Peruani). 

Escribir que iria en cada capitulo relacionado a los modelos basados en agentes. Pensando en capitulos y en papers a publicar. 
Algo para el segundo cap tal vez es lo de las graph neural networks para hacer ABC con los datos de las ovejas. El problema con esto es que no es trivial, podrias hacer un phd con esto. Tal vez podes hacer algo como lo que hizo sofi, que lo hizo en un espacio homogeneo. Hacerlo en un espacio heterogeneo ya seria algo bueno como para publicar en algun lado. 




6 de septiembre llegaria a escocia. 










Cuestiones del decodificador: 
usariamos ambos datasets, el de sofi y el de mercedes. 


Tensorflow usa colin. 








------------------------- NOTAS EN PAPEL -------------
# Notas sobre modelo de simulacion de movimiento animal
ver paper de hank y hooten: Agent-based Inference for Animal Movement. (tambien escribiste al lado de esto: kernel con logisticta. cambios en comportamiento dan cambios en selec de habitat?)


Habitat selection en espacio continuo implicaría un step selection poco eficiente. 


Punto de repulsión. (entiendo que esto lo escribiste cuando hablabas de areas de repulsion al modelar movimiento colectivo)


Todos ahora en mov animal están haciendo step selection y HMMs


Movimiento cuando los animales saben a donde quieren ir lo modelariamos con un biased correlated random walk. 

Step selection con regresiones. 

Contenedores: para descanso, exploracion, forrajeo 
Los contenedores se cargan de forma lineal y se descargan de forma lineal (aunque puede ser otra func como exponencial)
Estos contenedores son para hacer Recharge Dynamics, que los usamos para modelar transicion de comportamientos.
La idea es que el bicho que esta en un comportamiento determinado, por ejemplo el de forrajeo, se le va cargando el 
contenedor de "alimento" y la probabilidad de dejar de forrajear es funcion de cuan lleno este ese contenedor. 
Vamos a iniciar recharge dynamics para forrajeo y despues vemos si lo extendemos a mas comportamientos. 



Ver cuestiones alometricas para incluir en el modelo en el paper de elks de pajaro (2005 o 2004)


Definir donde el bicho quiere ir es una gran cuestion. 
Ver papers de elks reintroducidos


Los Integral Projection Model -> son extension de modelos matriciales. 



Switch de comportamiento informado por estado interno es una posibilidad, pero puede ser reemplazado por Recharge Dynamics. 


La energia que gana el bicho se va a crecimiento o a reservas. (en el modelo de sim de pajaro, al final del dia
se decide a donde va la energia, si a crecimiento o a reservas)


Necesitamos tener una forma de contabilidad de tiempo pasado en cada comportamiento y de distancia de desplazamiento

Energia de balance = Energia consumida - Energia gastada en locomocion

80% de grasa y 20% de proteina. 

Las ovejas de Pilca tienen un dt de 5 minutos. 

dt razonable segun pajaro -> 1 hora. 



Direccion de movimiento se computa a cada t?


Agents -> ICS (Internal Control System)

Read Paper called Collective Behaviour from surprise minimization. The paper talks about the Social Dilema (individual interest vs Collective Interest), about models of bounded rationality and subject rationality, and also about observing pulling and anchoring in movement behaviours. 




usar un dt de minutos. 

escala de grupos: modelar unas semanas (aca se pueden ignorar muchas cosas, como reproduccion, y se puede tener un dt de minuto)
escala poblacional: modelar por ejemplo un año o mas. esto implica eventos de reproduccion, etc 


recharge dynamics puede ser demasiado costoso computacionalmente porque implicaria evaluar una prob en cada dt, tal vez se puede aproximar con algo menos costoso usando algo como tiempos en los que pasa en cada comportamiento


# Experimentos

Experimentos a hacer con modelo de simulacion: 
- Exp 1 animales +o- selectivos con el habitat. 
- Exp 2 conflicto entre benficio del individuo y beneficio del grupo. 





# Notas sobre transformers (charla con Colin)

Train on 80% of individuals and test in the rest

dropout can reduce overfitting

Try a very small CNN


probar vision transformer -> Puede prestar atencion a toda la imagen, la covnet solo "mira a 3 lugares" (revisar si esto ultimo que escribiste esta bien)










# Caps de tesis
Cap1 -> Decoder
Cap2 -> Modelo de simulacion
Cap3 -> experimentos de simulacion y/o ajuste de modelo de simulacion a datos. 



# Papers
Decoder paper en ecologia -> un poco de docencia sobre como funcionan y como usarlos. 

